added some mods

diff --git a/.github/workflows/build_run_ios_simulator.yml b/.github/workflows/build_run_ios_simulator.yml
--- a/.github/workflows/build_run_ios_simulator.yml
+++ b/.github/workflows/build_run_ios_simulator.yml
@@ -81,40 +81,35 @@ jobs:
             fi
           done
       # Step 7: Install the .app file to the Simulator
-      - name: Install App to Simulator
-        run: |
-          # Find the most recent DerivedData folder
-          DERIVED_DATA_PATH=$(find ~/Library/Developer/Xcode/DerivedData -name "RxAlamofire*" -type d | head -n 1)
-          
-          # Debug print: Show the derived data path
-          echo "Derived Data Path: $DERIVED_DATA_PATH"
-      
-          # Define the app path
-          APP_PATH="${DERIVED_DATA_PATH}/Build/Products/Debug-iphonesimulator/RxAlamofire.app"
-          
-          # Debug print: Show the .app path
-          echo "App Path: $APP_PATH"
-      
-          # Check if the .app file exists
-          if [ -d "$APP_PATH" ]; then
-            echo "Found .app file at: $APP_PATH"
-          else
-            echo "Error: .app file not found at the expected path: $APP_PATH"
-            exit 1
-          fi
-      
-          # Install the app to the simulator
-          echo "Installing app to simulator..."
-          xcrun simctl install booted $APP_PATH
-      
-          # Debug: Check if the app was successfully installed
-          INSTALL_STATUS=$(xcrun simctl listapps booted | grep -E "RxAlamofire")
-          if [ -z "$INSTALL_STATUS" ]; then
-            echo "Error: Failed to install the app to the simulator."
-            exit 1
-          else
-            echo "App installed successfully to the simulator."
-          fi
+      # Step 7: Install the .app file to the Simulator
+    - name: Install App to Simulator
+      run: |
+        # Find the most recent DerivedData folder
+        DERIVED_DATA_PATH=$(find ~/Library/Developer/Xcode/DerivedData -name "RxAlamofire*" -type d | head -n 1)
+
+        # Print the DerivedData path for debugging
+        echo "Derived Data Path: $DERIVED_DATA_PATH"
+
+        # Check if the 'Build' folder exists
+        if [ ! -d "$DERIVED_DATA_PATH/Build" ]; then
+          echo "Error: Build folder not found in DerivedData."
+          exit 1
+        fi
+
+        # Find the .app file in the correct Build folder
+        APP_PATH=$(find "$DERIVED_DATA_PATH/Build/Products" -name "RxAlamofire.app" | head -n 1)
+
+        # Print the app path for debugging
+        echo "App Path: $APP_PATH"
+
+        # Check if the .app file exists
+        if [ ! -f "$APP_PATH" ]; then
+          echo "Error: .app file not found at the expected path: $APP_PATH"
+          exit 1
+        fi
+
+        # Install the app to the simulator
+        xcrun simctl install booted "$APP_PATH"
       # Step 7: Launch the App on the Simulator
       - name: Launch App on Simulator
         run: |
